# Generated by Django 4.2.4 on 2023-08-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('experience', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.userlevel'),
            preserve_default=False,
        ),
    ]
