# Generated by Django 4.2.4 on 2023-08-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlevel_customuser_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='level',
            new_name='levels',
        ),
    ]
