# Generated by Django 4.2.4 on 2023-08-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='levels',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.userlevel'),
            preserve_default=False,
        ),
    ]
