# Generated by Django 4.2.4 on 2023-08-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
