# Generated by Django 4.2.4 on 2023-08-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='comment',
            field=models.ManyToManyField(related_name='comments', to='placeapi.placecomment'),
        ),
    ]
