# Generated by Django 4.2.4 on 2023-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0002_placeinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
