# Generated by Django 4.2.4 on 2023-08-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0002_placeinfo_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeinfo',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='open_statuses',
            field=models.ManyToManyField(related_name='open_statuses', to='placeapi.placeopenstatus'),
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='ratings',
            field=models.ManyToManyField(related_name='ratings', to='placeapi.placerating'),
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='sub_images',
            field=models.ManyToManyField(related_name='sub_images', to='placeapi.placeimage'),
        ),
    ]
