# Generated by Django 4.2.4 on 2023-08-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0003_rename_comment_placeinfo_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceSubInfo',
        ),
    ]
