# Generated by Django 4.2.4 on 2023-08-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0004_alter_placeinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
