# Generated by Django 4.2.4 on 2023-08-12 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placeapi', '0006_placecomment_user_id_placeopenstatus_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placerating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='placerating',
            name='place',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='placeapi.placeinfo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='placerating',
            unique_together={('user', 'place')},
        ),
    ]
