# Generated by Django 4.2.4 on 2023-08-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0008_alter_placerating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeopenstatus',
            name='user_id',
        ),
        migrations.AddField(
            model_name='placeopenstatus',
            name='username',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
