# Generated by Django 4.2.4 on 2023-08-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0009_remove_placeopenstatus_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeopenstatus',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
