# Generated by Django 4.2.4 on 2023-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapi', '0010_alter_placeopenstatus_status_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placecomment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='placecomment',
            name='username',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
